<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            ['name' => 'Paracetamol 500mg (Panadol)', 'brand' => 'MediCure', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Fever', 'price' => 120, 'pack_size' => 10, 'unit_label' => 'tablet', 'manufacturer' => 'MediCure Labs', 'description' => 'Paracetamol helps reduce fever and relieve mild to moderate pain.', 'usage' => 'Adults: 500mg every 4–6 hours as needed. Do not exceed 4g/day.', 'aliases' => ['panadol', 'paracetamol', 'acetaminophen'], 'image_key' => '1'],
            ['name' => 'Cetirizine 10mg', 'brand' => 'AllerGo', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Allergy', 'price' => 90, 'pack_size' => 10, 'unit_label' => 'tablet', 'manufacturer' => 'AllerGo Pharma', 'description' => 'Antihistamine for sneezing, runny nose, itchy eyes.', 'usage' => 'Adults: 10mg once daily.', 'aliases' => ['cetirizine', 'rigix', 'aller'], 'image_key' => '2'],
            ['name' => 'Amoxicillin 500mg', 'brand' => 'BioPharm', 'category' => 'Medicine', 'type' => 'Capsule', 'illness' => 'Infection', 'price' => 350, 'pack_size' => 12, 'unit_label' => 'capsule', 'manufacturer' => 'BioPharm Pvt Ltd', 'description' => 'Broad-spectrum antibiotic. Use only on doctor advice.', 'usage' => '500mg every 8 hours for 5–7 days or as prescribed.', 'aliases' => ['amoxicillin', 'amoxil'], 'image_key' => '5'],
            ['name' => 'Vitamin D3 1000IU', 'brand' => 'NutriPlus', 'category' => 'Health Supplement', 'type' => 'Softgel', 'illness' => 'Supplement', 'price' => 500, 'pack_size' => 30, 'unit_label' => 'softgel', 'manufacturer' => 'NutriPlus Nutrition', 'description' => 'Supports bone health and immunity.', 'usage' => '1 softgel daily with a meal.', 'aliases' => ['vitamin d', 'd3'], 'image_key' => '3'],
            ['name' => 'Cough Syrup 100ml', 'brand' => 'CoughCare', 'category' => 'Winter Essential', 'type' => 'Syrup', 'illness' => 'Cough', 'price' => 220, 'pack_size' => 1, 'unit_label' => 'bottle', 'manufacturer' => 'CoughCare Remedies', 'description' => 'Soothes throat irritation and cough.', 'usage' => 'Adults: 10ml 3 times daily after meals.', 'aliases' => ['cough syrup', 'coughcare'], 'image_key' => '4'],
            ['name' => 'Ibuprofen 200mg', 'brand' => 'PainAway', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Pain', 'price' => 140, 'pack_size' => 10, 'unit_label' => 'tablet', 'manufacturer' => 'PainAway Healthcare', 'description' => 'NSAID for pain, inflammation and fever.', 'usage' => 'Adults: 200–400mg every 6–8 hours with food.', 'aliases' => ['ibuprofen', 'brufen', 'painaway'], 'image_key' => '6'],
            ['name' => 'Vicks Vapor Rub 50g', 'brand' => 'WinterCare', 'category' => 'Winter Essential', 'type' => 'Ointment', 'illness' => 'Cold', 'price' => 280, 'pack_size' => 1, 'unit_label' => 'jar', 'manufacturer' => 'WinterCare', 'description' => 'Relieves nasal congestion and cough.', 'usage' => 'Apply on chest and throat before sleep.', 'aliases' => ['vicks', 'vapor rub'], 'image_key' => '4'],
            ['name' => 'Moisturizing Face Cream', 'brand' => 'DermaGlow', 'category' => 'Skin Care', 'type' => 'Cream', 'illness' => 'Dry Skin', 'price' => 650, 'pack_size' => 1, 'unit_label' => 'tube', 'manufacturer' => 'DermaGlow', 'description' => 'Hydrating cream for dry and sensitive skin.', 'usage' => 'Apply twice daily on clean face.', 'aliases' => ['moisturizer', 'face cream'], 'image_key' => '3'],
            ['name' => 'Baby Diapers Pack (M)', 'brand' => 'MomCare', 'category' => 'Mom & Baby', 'type' => 'Diaper', 'illness' => 'Baby Care', 'price' => 1200, 'pack_size' => 1, 'unit_label' => 'pack', 'manufacturer' => 'MomCare', 'description' => 'Soft absorbent diapers for infants.', 'usage' => 'Change every 3–4 hours or as needed.', 'aliases' => ['diaper', 'baby diaper'], 'image_key' => '1'],
            ['name' => 'Glucometer Kit', 'brand' => 'DiabetCheck', 'category' => 'Diabetic Care', 'type' => 'Device', 'illness' => 'Diabetes', 'price' => 2500, 'pack_size' => 1, 'unit_label' => 'kit', 'manufacturer' => 'DiabetCheck', 'description' => 'Digital blood glucose monitoring kit.', 'usage' => 'Use as directed in manual.', 'aliases' => ['glucometer', 'sugar test'], 'image_key' => '6'],
            ['name' => 'Digital BP Monitor', 'brand' => 'MediDevice', 'category' => 'Medical Devices', 'type' => 'Device', 'illness' => 'Hypertension', 'price' => 3200, 'pack_size' => 1, 'unit_label' => 'device', 'manufacturer' => 'MediDevice', 'description' => 'Automatic upper-arm blood pressure monitor.', 'usage' => 'Measure seated and relaxed.', 'aliases' => ['bp monitor', 'blood pressure'], 'image_key' => '5'],
            ['name' => 'Arnica 30C', 'brand' => 'HomeoHeal', 'category' => 'Homeopathy', 'type' => 'Globules', 'illness' => 'Pain', 'price' => 180, 'pack_size' => 1, 'unit_label' => 'bottle', 'manufacturer' => 'HomeoHeal', 'description' => 'Homeopathic remedy for bruises and muscle soreness.', 'usage' => 'As directed by homeopathic physician.', 'aliases' => ['arnica', 'homeopathy'], 'image_key' => '2'],
            ['name' => 'Wellness Support Capsules', 'brand' => 'VitaWell', 'category' => 'Sexual Wellness', 'type' => 'Capsule', 'illness' => 'Wellness', 'price' => 890, 'pack_size' => 6, 'unit_label' => 'capsule', 'manufacturer' => 'VitaWell', 'description' => 'Dietary supplement for general wellness.', 'usage' => 'As directed on label.', 'aliases' => ['wellness', 'vitawell'], 'image_key' => '3'],
            ['name' => 'Amlodipine 5mg', 'brand' => 'CardioCare', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Hypertension', 'price' => 180, 'pack_size' => 10, 'unit_label' => 'tablet', 'manufacturer' => 'CardioCare Pharma', 'description' => 'Calcium channel blocker for high blood pressure.', 'usage' => '1 tablet once daily or as prescribed.', 'aliases' => ['amlodipine', 'norvasc'], 'image_key' => '5'],
            ['name' => 'Telmisartan 40mg', 'brand' => 'CardioCare', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Hypertension', 'price' => 260, 'pack_size' => 10, 'unit_label' => 'tablet', 'manufacturer' => 'CardioCare Pharma', 'description' => 'ARB used to treat hypertension.', 'usage' => '1 tablet once daily.', 'aliases' => ['telmisartan', 'micardis'], 'image_key' => '6'],
            ['name' => 'Aspirin 75mg', 'brand' => 'HeartPlus', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Cardiac', 'price' => 70, 'pack_size' => 14, 'unit_label' => 'tablet', 'manufacturer' => 'HeartPlus', 'description' => 'Low-dose aspirin for cardiovascular protection.', 'usage' => '1 tablet daily after food.', 'aliases' => ['aspirin', 'disprin', 'asa'], 'image_key' => '1'],
            ['name' => 'Augmentin 625mg', 'brand' => 'BioPharm', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Infection', 'price' => 480, 'pack_size' => 10, 'unit_label' => 'tablet', 'manufacturer' => 'BioPharm Pvt Ltd', 'description' => 'Amoxicillin with clavulanic acid.', 'usage' => '1 tablet twice daily for 5–7 days.', 'aliases' => ['augmentin', 'amoxicillin clavulanate'], 'image_key' => '5'],
            ['name' => 'Montelukast 10mg', 'brand' => 'AllerGo', 'category' => 'Medicine', 'type' => 'Tablet', 'illness' => 'Allergy', 'price' => 320, 'pack_size' => 10, 'unit_label' => 'tablet', 'manufacturer' => 'AllerGo Pharma', 'description' => 'Leukotriene receptor antagonist for asthma and allergy.', 'usage' => '1 tablet at night.', 'aliases' => ['montelukast', 'singulair'], 'image_key' => '2'],
        ];

        foreach ($rows as $row) {
            Medicine::updateOrCreate(['name' => $row['name']], $row);
        }
    }
}
